const dex = require('../')
const { setTimeout } = require('timers/promises')
dex.network.on('ready', async () => {
    await setTimeout(2000)
    const order = await dex.createOrder('SELL', 1, 'BTC', 'abc.eth')
    await setTimeout(5000)
    console.log("ORDERBOOK", dex.getOrderbook())
    const order2 = await dex.createOrder('SELL', 1, 'ETH', 'abc.eth')
    await dex.cancelOrder(order2.id)
    await setTimeout(2000)
    console.log("ORDERBOOK", dex.getOrderbook())
})
